"""Add subuser meta and max_subusers

Revision ID: 03ddd083d84f
Revises: f4dec2ca4200
Create Date: 2026-08-10 06:26:23.330430+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ddd083d84f'
down_revision: Union[str, None] = 'f4dec2ca4200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_sub_user_id'), ['sub_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'sub_users', ['sub_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requests_sub_user_id'))
        batch_op.drop_column('sub_user_id')

    # ### end Alembic commands ###
