"""Add subuser metadata fields

Revision ID: 35c7248d84fb
Revises: 03ddd083d84f
Create Date: 2026-08-10 06:26:50.425572+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35c7248d84fb'
down_revision: Union[str, None] = '03ddd083d84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_request_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('request_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_subusers', sa.Integer(), server_default='10', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('max_subusers')

    with op.batch_alter_table('sub_users', schema=None) as batch_op:
        batch_op.drop_column('meta')
        batch_op.drop_column('request_count')
        batch_op.drop_column('last_request_ip')
        batch_op.drop_column('last_request_at')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
