"""Add allowed_indices to users replica table

Revision ID: 8af728bbe7c3
Revises: 76f6675800f9
Create Date: 2025-10-15 05:08:30.785776+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8af728bbe7c3'
down_revision: Union[str, None] = '76f6675800f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_indices', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allowed_indices')

    # ### end Alembic commands ###
