"""Add SyncHistory

Revision ID: 327bef145ceb
Revises: f1a2b3c4d5e6
Create Date: 2026-06-04 08:53:23.078833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '327bef145ceb'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_history_operation_type'), 'sync_history', ['operation_type'], unique=False)
    op.create_index(op.f('ix_sync_history_status'), 'sync_history', ['status'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_component'), 'system_logs', ['component'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('requests_pending', sa.Integer(), nullable=True),
    sa.Column('requests_completed', sa.Integer(), nullable=True),
    sa.Column('requests_failed', sa.Integer(), nullable=True),
    sa.Column('avg_processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.drop_table('elasticsearch_config')
    op.alter_column('request_types', 'elasticsearch_query_template',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('user_request_access', 'max_requests_per_day')
    op.drop_column('user_request_access', 'max_requests_per_month')
    op.create_foreign_key(None, 'users', 'profile_type_configs', ['profile_type'], ['name'])
    op.drop_column('users', 'priority')
    op.drop_column('users', 'rate_limit_per_day')
    op.drop_column('users', 'blocked_request_types')
    op.drop_column('users', 'rate_limit_per_minute')
    op.drop_column('users', 'synced_at')
    op.drop_column('users', 'rate_limit_per_hour')
    op.drop_column('users', 'allowed_request_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_request_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rate_limit_per_hour', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rate_limit_per_minute', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('blocked_request_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rate_limit_per_day', sa.INTEGER(), server_default=sa.text('500'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('priority', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('user_request_access', sa.Column('max_requests_per_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_request_access', sa.Column('max_requests_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('request_types', 'elasticsearch_query_template',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_table('elasticsearch_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('verify_ssl', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='elasticsearch_config_pkey')
    )
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_component'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_sync_history_status'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_operation_type'), table_name='sync_history')
    op.drop_table('sync_history')
    # ### end Alembic commands ###
