"""Add uniqueness constraints for idempotency

Revision ID: 5d6fe8b796cf
Revises: a2866c53ac43
Create Date: 2026-08-26 12:15:11.057459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6fe8b796cf'
down_revision: Union[str, None] = 'a2866c53ac43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
