"""Refactor Request State Machine

Revision ID: a2866c53ac43
Revises: k1l2m3n4o5p6
Create Date: 2026-08-26 10:47:32.506996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2866c53ac43'
down_revision: Union[str, None] = 'k1l2m3n4o5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_requests', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('incoming_requests', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('incoming_requests', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incoming_requests', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incoming_requests', sa.Column('worker_id', sa.String(length=100), nullable=True))
    op.drop_column('incoming_requests', 'error_message')
    op.drop_column('incoming_requests', 'retry_count')
    op.alter_column('object_storage_configs', 'storage_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Storage provider type: minio, ceph, s3',
               existing_nullable=False,
               existing_server_default=sa.text("'minio'::character varying"))
    op.alter_column('object_storage_configs', 'endpoint_url',
               existing_type=sa.VARCHAR(length=500),
               comment='S3-compatible endpoint URL, e.g. http://192.168.1.10:9000',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'secret_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Fernet-encrypted secret key',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'default_bucket',
               existing_type=sa.VARCHAR(length=255),
               comment='Default bucket name to use when not specified in query',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'path_style',
               existing_type=sa.BOOLEAN(),
               comment='Use path-style addressing (required for MinIO/Ceph)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('object_storage_configs', 'timeout',
               existing_type=sa.INTEGER(),
               comment='Connection timeout in seconds',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.drop_constraint('object_storage_configs_name_key', 'object_storage_configs', type_='unique')
    op.drop_index('ix_object_storage_configs_name', table_name='object_storage_configs')
    op.create_index(op.f('ix_object_storage_configs_name'), 'object_storage_configs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_storage_configs_name'), table_name='object_storage_configs')
    op.create_index('ix_object_storage_configs_name', 'object_storage_configs', ['name'], unique=False)
    op.create_unique_constraint('object_storage_configs_name_key', 'object_storage_configs', ['name'])
    op.alter_column('object_storage_configs', 'timeout',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Connection timeout in seconds',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('object_storage_configs', 'path_style',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Use path-style addressing (required for MinIO/Ceph)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('object_storage_configs', 'default_bucket',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Default bucket name to use when not specified in query',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'secret_key_encrypted',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted secret key',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'endpoint_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='S3-compatible endpoint URL, e.g. http://192.168.1.10:9000',
               existing_nullable=False)
    op.alter_column('object_storage_configs', 'storage_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Storage provider type: minio, ceph, s3',
               existing_nullable=False,
               existing_server_default=sa.text("'minio'::character varying"))
    op.add_column('incoming_requests', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('incoming_requests', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('incoming_requests', 'worker_id')
    op.drop_column('incoming_requests', 'lease_until')
    op.drop_column('incoming_requests', 'last_attempt_at')
    op.drop_column('incoming_requests', 'last_error')
    op.drop_column('incoming_requests', 'attempt_count')
    # ### end Alembic commands ###
