"""Add uniqueness constraints for idempotency

Revision ID: 224b2f2a35aa
Revises: 8b32bd664f8a
Create Date: 2026-08-26 12:14:20.566102+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224b2f2a35aa'
down_revision: Union[str, None] = '8b32bd664f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
