"""Add missing user columns

Revision ID: 626f951b6799
Revises: e71a9886c93a
Create Date: 2026-06-16 11:52:58.071040+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626f951b6799'
down_revision: Union[str, None] = 'e71a9886c93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enterprise_user_id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_users_enterprise_user_id'), ['enterprise_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_users_external_user_id'), ['external_user_id'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('export_batch_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_export_batch_id'), ['export_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_sync_status'), ['sync_status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subuser_rate_limit_per_minute', sa.Integer(), server_default='10', nullable=False))
        batch_op.add_column(sa.Column('subuser_rate_limit_per_hour', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('subuser_rate_limit_per_day', sa.Integer(), server_default='500', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subuser_rate_limit_per_day')
        batch_op.drop_column('subuser_rate_limit_per_hour')
        batch_op.drop_column('subuser_rate_limit_per_minute')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_sync_status'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_export_batch_id'))
        batch_op.drop_column('export_batch_id')
        batch_op.drop_column('sync_status')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sub_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_users_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_sub_users_enterprise_user_id'))

    op.drop_table('sub_users')
    # ### end Alembic commands ###
