"""Refactor Request State Machine

Revision ID: 8b32bd664f8a
Revises: 35c7248d84fb
Create Date: 2026-08-26 10:43:35.150740+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b32bd664f8a'
down_revision: Union[str, None] = '35c7248d84fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('worker_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('error_message')
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('worker_id')
        batch_op.drop_column('lease_until')
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('last_error')
        batch_op.drop_column('attempt_count')

    # ### end Alembic commands ###
